from django.conf.urls import include, url

import dwclasses.views as views


urlpatterns = [
    url(r'^compendiumclasses/?$',
        views.ListCompendiumClassesView.as_view()),
    url(r'^compendiumclasses/create',
        views.CreateCompendiumClassView.as_view()),
    url(r'^compendiumclasses/default',
        views.DefaultCompendiumClassView.as_view()),
    url(r'^compendiumclasses/(?P<cc_id>\d+)/?$',
        views.EditCompendiumClassView.as_view()),
    url(r'^compendiumclasses/(?P<cc_id>\d+)/create_section',
        views.CreateSectionView.as_view()),
    url(r'^compendiumclasses/(?P<cc_id>\d+)/edit_section/(?P<sec_id>\d+)',
        views.EditSectionInlineView.as_view()),
    url(r'^compendiumclasses/(?P<cc_id>\d+)/remove_section/(?P<sec_id>\d+)',
        views.RemoveSectionView.as_view()),
    url(r'^compendiumclasses/(?P<cc_id>\d+)/link_section',
        views.LinkSectionView.as_view()),
    url(r'^combinedclasses/?$',
        views.ListCombinedClassesView.as_view()),
    url(r'^combinedclasses/create',
        views.CreateCombinedClassView.as_view()),
    url(r'^combinedclasses/(?P<id>\d+)/edit',
        views.EditCombinedClassView.as_view()),
    url(r'^combinedclasses/(?P<id>\d+)/new_character',
        views.NewCharacterView.as_view()),
    url(r'^characters/(?P<id>\d+)',
        views.ViewCharacterView.as_view()),
    url(r'^characters/?$',
        views.ListCharacterView.as_view()),
    url(r'^dwclass/?$',
        views.DWClassListView.as_view()),
    url(r'^dwclass/create',
        views.DWClassCreateView.as_view()),
    url(r'^dwclass/(?P<id>\d+)',
        views.DWClassEditView.as_view()),
    url(r'^preview/?$',
        views.PreviewListView.as_view()),
    url(r'^preview/(?P<id>\d+)',
        views.DWClassPreView.as_view()),
    url(r'^print/(?P<id>\d+)/?$',
        views.DWClassPreView.as_view(
            template_name='class_create_print.html')),
    url(r'^print/(?P<id>\d+)/levelup',
        views.DWClassPreView.as_view(
            template_name='class_levelup_print.html')),
]
